<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <Threshold>80</Threshold>
    <ThresholdType>line</ThresholdType>
    <ThresholdStat>total</ThresholdStat>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotInfraKit.Testing\DotInfraKit.Testing.csproj" />
    <ProjectReference Include="..\..\src\DotInfraKit.Testing.FluentAssertions\DotInfraKit.Testing.FluentAssertions.csproj" />
    <!-- Queue and Cache are bundled into DotInfraKit.Testing.nupkg but PrivateAssets="all" hides them from ProjectReference consumers -->
    <ProjectReference Include="..\..\src\DotInfraKit.Queue\DotInfraKit.Queue.csproj" />
    <ProjectReference Include="..\..\src\DotInfraKit.Cache\DotInfraKit.Cache.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
